# Generated by Django 5.1.5 on 2025-05-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='code',
            field=models.CharField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='taxcategory',
            name='code',
            field=models.CharField(blank=True, editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together={('code', 'company_id', 'branch_id')},
        ),
        migrations.AlterUniqueTogether(
            name='taxcategory',
            unique_together={('code', 'company_id', 'branch_id')},
        ),
    ]
