# Generated by Django 5.1.5 on 2025-05-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_alter_tax_code_alter_taxcategory_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='taxcategory',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=52, null=True),
        ),
    ]
