# Generated by Django 5.1.5 on 2025-05-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_alter_tax_code_alter_taxcategory_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taxcategory',
            unique_together=set(),
        ),
    ]
